version: '3.7'

services:

  statping:
    image: mylinode/statping:latest
    build:
      context: ./docker
      args:
        STATPING_VERSION: latest
    volumes:
      - ./statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080


# focusdb:
#     image: $REPONAME/focusdb
#     build:
#       context: ./postgres
#       args:
#         POSTGRES_VERSION: ${POSTGRES_VERSION}
#     environment:
#       - POSTGRES_USER=focus
#       - POSTGRES_DB=focus
#       - POSTGRES_PASSWORD=focus
#     ports:
#       - $POSTGRES_PORT:5432
# volumes:
#   statping_data:
#     driver: local
