---
# Ansible playbook to create a linode.  A new linode will be created for each
# playbook run.  Note that this playbook is run on the localhost and uses the
# linode_v4 API.  Configure variables in group_vars/all.yml.
- name: Create Linode
  gather_facts: no
  hosts: localhost
  tasks:
  - name: Create a new Linode.
    linode_v4:
      label: "{{ label }}{{ 100 |random }}"
      access_token: "{{ token }}"
      type: g6-nanode-1
      region: us-east
      image: linode/debian9
      root_pass: "{{ password }}"
      authorized_keys: "{{ ssh_keys }}"
      group: example_group
      tags: example_group "creator:ansible"
      state: present
    register: new_linode

  - name: Print info about the new Linode instance
    debug:
      msg: "ID is {{ new_linode.instance.id }} and IP is {{ new_linode.instance.ipv4 }}"
            
