# Simple script to take json output from linode's dynamic ansible inventory
# and generate output to create an ansible inventory file.
# 
# Usage:
#     ansible-inventory -i linode.yml --list | python3 inventory.py

import sys, json
from datetime import datetime

# Read json from standard input
j = json.load(sys.stdin)

# Grab the main list of hosts
hosts_json = j['_meta']['hostvars']

print("# inventory.yml")
print("# autogenerated file.  Do not edit directly.")
print(f"# Generated: {datetime.now()}")
print("# ---------------------------------------------------------------\n")

print("linode:")
print("  hosts:")

for k in hosts_json.keys():
  print(f'    {k}:')
  print(f'      ansible_host: {hosts_json[k]["ipv4"][0]}\n')


print("  children:")

for g in j['all']['children']:
  if g != "ungrouped":
    print(f'    {g}:')
    print(f'      hosts:')
    for h in j[g]['hosts']:
      print(f'        {h}:')
